# Generated by Django 4.1 on 2022-08-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='nro_calle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='provincia',
            field=models.CharField(max_length=255),
        ),
    ]
