# Generated by Django 4.1 on 2022-08-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_apellido_alter_cliente_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='id_direccion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
