# Generated by Django 4.1 on 2022-08-16 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_direccion_id_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cuenta', models.CharField(choices=[('C', 'CLASSIC'), ('G', 'GOLD'), ('B', 'BLACK')], default='C', max_length=20)),
                ('saldo', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='direccion',
            new_name='iddireccion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='idcuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cuenta'),
        ),
    ]
