# Generated by Django 4.1 on 2022-08-27 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cuenta_rename_direccion_cliente_iddireccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='idsucursal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.sucursal'),
        ),
    ]
