# Generated by Django 4.1 on 2022-08-29 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_authuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='iddireccion',
            new_name='direccion',
        ),
    ]
