# Generated by Django 4.1 on 2022-08-16 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0004_cuenta_rename_direccion_cliente_iddireccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('tipo_prestamo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
    ]
