# Generated by Django 4.1 on 2022-08-26 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cuenta_rename_direccion_cliente_iddireccion_and_more'),
        ('prestamo', '0002_alter_prestamo_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cuenta'),
        ),
    ]
