# Generated by Django 4.1 on 2022-08-27 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_sucursal_cliente_idsucursal'),
        ('prestamo', '0002_alter_prestamo_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.sucursal'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cuenta'),
        ),
    ]
